# Generated by Django 4.0.5 on 2022-06-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighborhood_id',
            new_name='neighborhood',
        ),
    ]
