# Generated by Django 4.0.5 on 2022-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants_count',
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='health_tell',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
