# Generated by Django 4.0.5 on 2022-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_neighborhood_id_business_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
